import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString, IsOptional } from 'class-validator';

export class VerifyPaymentDto {
  @ApiProperty({ description: 'The booking reference ID' })
  @IsString()
  @IsNotEmpty()
  bookingReference: string;

  @ApiProperty({ description: 'The payment ID generated by our backend previously' })
  @IsString()
  @IsNotEmpty()
  paymentId: string;

  @ApiProperty({ description: 'The payment token or signature returned by the provider' })
  @IsString()
  @IsOptional()
  paymentToken?: string;
}
